# Generated by Django 5.2.8 on 2025-12-26 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
