# Generated by Django 5.2.8 on 2025-12-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otpcode_phone_number_otpcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Phone Number'),
        ),
    ]
