# Generated by Django 5.2.8 on 2026-01-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cartitem_product_image_and_more"),
        ("products", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(verbose_name="Quantity"),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"), name="unique_cart_product"
            ),
        ),
    ]
